### ISSUE TITLE
How to add missing API

### ISSUE THREAD

**Issue by Leko** [APIs-guru/api-models#102]
Hi there

I want to add missing API `/auth.test` about [Slack](https://github.com/APIs-guru/api-models/tree/master/APIs/slack.com/1.0.0/swagger.yaml).

But all `swagger.yaml` in this repository seem generated from `info.x-origin.url` source.
So I think I cannot modify `swagger.yaml` directly.

I should modify swagger.yaml directly, or modify patch, or send pull request to `x-origin` repository ?
Please teach me how to contribute to this repository.

```json
{
  "paths": {
    "/auth.test": {
      "get": {
        "description": "This method checks authentication and tells you who you are.",
        "responses": {
          "200": {
            "description": "OK",
            "schema": {
              "type": "object",
              "properties": {
                "ok": { "type": "boolean" },
                "url": { "type": "string" },
                "team": { "type": "string" },
                "user": { "type": "string" },
                "team_id": { "type": "string" },
                "user_id": { "type": "string" }
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by IvanGoncharov** [comment]
Hi @Leko 

> I want to add missing API /auth.test about Slack.

It would be great 👍 

> But all swagger.yaml in this repository seem generated from info.x-origin.url source.
So I think I cannot modify swagger.yaml directly.

Yes, you right 😞 

> or send pull request to x-origin repository ?

you can try, but in my experience, they will ignore your PRs/issues.
Take a look at repo for Github spec: https://github.com/raml-apis/GitHub/pulls
And since they never update specs I don't think it make sense use them in `x-origin`.

I thinking about creating separate `APIs-guru/unofficial_openapi_specs` repo move slack spec there and change `x-origin` to it.
@Leko What do you think?

**Comment by Leko** [comment]
@IvanGoncharov I'm sorry for late reply.

> And since they never update specs

hm... I think so too.

> I thinking about creating separate APIs-guru/unofficial_openapi_specs repo move slack spec there and change x-origin to it.

Sounds good.

**Comment by IvanGoncharov** [comment]
@Leko I created repo: https://github.com/APIs-guru/unofficial_openapi_specs
And give you write access, use if wisely 😉

**Comment by Leko** [comment]
@IvanGoncharov Thank you so much :+1:

**Comment by Leko** [comment]
@IvanGoncharov An error occured:

```
ERROR: Permission to APIs-guru/unofficial_openapi_specs.git denied to Leko.
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
```

Please check access settings.

**Comment by IvanGoncharov** [comment]
![image](https://cloud.githubusercontent.com/assets/8336157/17777317/ca659c1e-6568-11e6-8d37-f16fe6e964cc.png)
You need to accept invitation

**Comment by IvanGoncharov** [comment]
@Leko You should get email from GitHub.
Maybe it went to `Spam` or something.

**Comment by Leko** [comment]
> You should get email from GitHub.

Ah, sorry. I mistake.  
I push to Github after accept invite, it works fine.
