### ISSUE TITLE
Add "Medium.com" API

### ISSUE THREAD

**Issue by amardeshbd** [APIs-guru/api-models#105]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: NO
**Url**: https://raw.githubusercontent.com/amardeshbd/medium-api-specification/master/medium-api-specification.yaml
**Name**: Medium.com

Project Page: https://github.com/amardeshbd/medium-api-specification
Logo: https://raw.githubusercontent.com/Medium/medium-logos/master/logo/medium-m-color-200px.png (Source: https://github.com/Medium/medium-logos/tree/master/logo)

**Comment by IvanGoncharov** [comment]
@amardeshbd Thank you a lot.
Will add in a moment.

**Comment by IvanGoncharov** [comment]
@amardeshbd I added your repo to list of spec sources:
https://github.com/APIs-guru/api-models#spec-sources

We want to motivate more developers to write Swagger specs for API they are using.
It would be great to know what motivate your to write Swagger spec for Medium?

**Comment by amardeshbd** [comment]
I think it has more to do it the awareness of API spec standard such as _'OpenAPI Specification'_. Once people know what it is, and benefits, I don't think there would be much reason not to publish API spec different format that this open standard.

For me, I was impressed with the variety of tools that supports _'OpenAPI Specification'_. So, I wanted to exercise my knowledge on writing specification. `medium.com`'s API doc seemed relatively very small to handle. So, wanted to port that over to OpenAPI spec. I hope this gives them something to discuss internally and someday adopt the standard to publish future API spec updates.

**Comment by amardeshbd** [comment]
Closed the issue, since **Medium.com** API spec is now live on [APIS.guru](https://apis.guru/browse-apis/) 😃
