### ISSUE TITLE
[enhancement] add list of models to the api-models page 

### ISSUE THREAD

**Issue by RomanGotsiy** [APIs-guru/api-models#17]
Currently this page  http://apis-guru.github.io/api-models/ returns 404 errer. It would be great if it had list of links to all the modles in this repo

**Comment by bobby-brennan** [comment]
Here's the link:
http://apis-guru.github.io/api-models/api/v1/list.json

Ivan, maybe redirect to that page from apis-guru.github.io/api-models?

Bobby Brennan
bobby.brennan@gmail.com

**Comment by IvanGoncharov** [comment]
@bobby-brennan I think it rude to show JSON as main page of site.
And I understand use case, Github disable CORS on raw links inside repo.
So if you want to use spec in some online service without proxy you need to make url http://apis-guru.github.io/api-models/ + <path inside repo> which is not so obvious and easy.
I think simple html with links to specs and small text section will satisfy all needs.

**Comment by RomanGotsiy** [comment]
I'm not sure but I believe that it's not possible to have redirects on Github pages.

**Comment by brennebeck** [comment]
I generally agree with this, there should definitely be something on the root page. But @IvanGoncharov - are you thinking this should be human friendly? Seems so by this comment:
> I think it rude to show JSON as main page of site.

If so, I think the main gh-page should default to a simple splash screen of all the models and they should link to the swagger,etc. generated docs with an additional link to the actual json. 

Thoughts?

**Comment by IvanGoncharov** [comment]
> they should link to the swagger,etc. generated docs

I think generating docs is out of scope of this project. I don't want to compete with companies which provide API related service, instead I want to supply them with API specs. So https://any-api.com/ is showing generated docs and https://sdks.io/ is generating SDKs. At the same time I want this project to be vendor-independent so I link them only in [this section](https://github.com/APIs-guru/api-models#integration-with-3rd-party-services).

 Ideally I want to create main page that explain this project([Reveal.js](http://lab.hakim.se/reveal-js/#/) is good candidate). But I don't have time and knowledge at the moment.

@RomanGotsiy pointed to real problem, at the moment it's hard to guess link to particular Swagger spec.
And thinking about KISS solution, very simple HTML with links like that:
```html
<a href="https://apis-guru.github.io/api-models/googleapis.com/drive/v1/swagger.json">
  googleapis.com/drive/v1/swagger.json
</a>
```
@brennebeck What do you think?

P.S. I'm gladly accept any help and I'm really open to PRs :)
If you have some questions you we can chat on [Gitter](https://gitter.im/APIs-guru/api-models?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

**Comment by brennebeck** [comment]
I definitely think linking to all the specs is better than 404'ing and is a good placeholder until something matching a proper explanation page, like you describe, is in place. 

Do you have any preference for a language or kit to automate the building of this? I have a few extra hours this week and would be glad to give it a go - nobody wants to manually edit that page with every addition, I'm sure ;)

**Comment by IvanGoncharov** [comment]
I use [collection.js](https://github.com/APIs-guru/api-models/blob/master/scripts/collection.js) script to do all operations with collection. 
After each commit [deploy_gh_pages.sh](https://github.com/APIs-guru/api-models/blob/master/scripts/deploy_gh_pages.sh) script is executed and it already have commands for generating CSV and REST API. 
You can add separate command to generate HTML, to get list of files use [getSpecs](https://github.com/APIs-guru/api-models/blob/master/scripts/collection.js#L670) function.

**Comment by brennebeck** [comment]
Thanks! I'll work on putting something together this week :+1:
