### ISSUE TITLE
Json Schema samples

### ISSUE THREAD

**Issue by sergey-tihon** [APIs-guru/api-models#20]
Why you converted all schemas in YAML format ?
Could you provide samples in both formats (JSON and YAML)?

**Comment by IvanGoncharov** [comment]
@sergey-tihon
> Why you converted all schemas in YAML format?

To help with maintenance: I manually fix and review specs and it easier to do in YAML.
Also in my experience most of handwritten specs are in YAML, so others developers also prefer it.
I disscuss all major changes on [Gitter](https://gitter.im/APIs-guru/api-models), you are welcome to subscribe and participate in disscussion.

> Could you provide samples in both formats (JSON and YAML)?

I see you are [using](https://github.com/sergey-tihon/SwaggerProvider/blob/831c298355ef100af587c0934ef260e4d6e9d390/tests/SwaggerProvider.Tests/Schema.Parser.Tests.fs#L29) APIs.json 
It was mistake, my intent was to use YAML only inside repo.
I fixed APIs.json to link JSON files.

**Comment by IvanGoncharov** [comment]
By the way thanks for [Expedia](https://www.expedia.com/static/mobile/swaggerui) link I will try to fix it.
If you know about other specs for public APIs missing from [this list](https://docs.google.com/spreadsheets/d/14zxKcW_Pzu5aYI3Tnwe5ph2Ru2pkSP8yHWEQhx3t8pI/edit?usp=sharing), please share it through separate issue.

**Comment by sergey-tihon** [comment]
@IvanGoncharov Thank you for fix.

>I manually fix and review specs and it easier to do in YAML.

Why manually?  Can not swagger-parer do it?

**Comment by sergey-tihon** [comment]
I use `APIs.json` in unit tests to check that my Swagger schema parser is able to parse all known Swagger schemas.
In the future I am going to [support Yaml schemas](https://github.com/sergey-tihon/SwaggerProvider/issues/3), so at the some point would be nice to have one file with all link to Yaml schemas.

**Comment by IvanGoncharov** [comment]
@sergey-tihon I answered you in Gitter.
We can chat there :)
