### ISSUE TITLE
Swagger file for APIs-guru REST API

### ISSUE THREAD

**Issue by colingoldberg** [APIs-guru/api-models#25]
Hi Ivan,

As we discussed, I would like to see a Swagger file for your REST API. I would then be able to import it into Ritc.

Regards

Colin Goldberg

**Comment by bobby-brennan** [comment]
+1, would be great to have swagger for APIs.guru

**Comment by IvanGoncharov** [comment]
@colingoldberg @bobby-brennan I wrote swagger file, official link is http://apis-guru.github.io/api-models/api/v1/swagger.yaml
I also added it into my collection.
If you have time please review it, comments and PRs are wil help me a lot.
File inside repo: https://github.com/APIs-guru/api-models/blob/master/scripts/apis_guru_swagger.yaml
