### ISSUE TITLE
bbc.co.uk Nitro API spec

### ISSUE THREAD

**Issue by MikeRalphson** [APIs-guru/api-models#29]
https://raw.githubusercontent.com/Mermade/bbcparse/master/nitroApi/swagger.json

Automatically generated from API's metadata feed

From the info section:

		"version": "1.0.0",
		"title": "BBC Nitro API",
		"description": "BBC Nitro is the BBC's application programming interface (API) for BBC Programmes Metadata.",
		"termsOfService": "http://www.bbc.co.uk/terms/",
		"contact": {
			"name": "Open Nitro Project",
			"email": "Jon.Billings@bbc.co.uk",
			"url": "http://developer.bbc.co.uk/"
		},
		"license": {
			"name": "Nitro Public License",
			"url": "https://developer.bbc.co.uk/nitropubliclicence/"
		}

**Comment by IvanGoncharov** [comment]
@MikeRalphson Thank you, your swagger spec looks very cool :+1: 
I rarely see Swagger spec with so much attention to details.
Can you please add [externalDocs](https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md#externalDocumentationObject) to make it perfect :smiley:
