### ISSUE TITLE
Uber and Instagram

### ISSUE THREAD

**Issue by mohsen1** [APIs-guru/api-models#3]
We have Uber and Instagram as examples [over Swagger Editor example files](https://github.com/swagger-api/swagger-editor/tree/master/app/spec-files). Instagram is not complete yet, I'm working on it. If you want to have those feel free to steal them from there

**Comment by IvanGoncharov** [comment]
@mohsen1 Thank you.

I don't have enough resources to manually  check and maintain validity of Swagger documents.
And my experience show that Google for example update it's API documents almost every day.

So for the time being, I'm focused only on official sources, this allow me to automatically update and react on all changes. I specify official link inside Swagger extension, like [here](https://github.com/APIs-guru/api-models/blob/master/clickmeter.com/v2/swagger.json#L16) or [here](https://github.com/APIs-guru/api-models/blob/master/googleapis.com/gmail/v1/swagger.json#L16) and use them inside update script.

Do you official URLs for these Swagger documents?
Or URLs to documents in any other format?
Can you please describe how you acquired information for this documents?

**Comment by mohsen1** [comment]
Nope. It's all done manually

**Comment by IvanGoncharov** [comment]
@mohsen1 I founder complete version of Instagram API here:
https://github.com/darklynx/swagger-api-collection
As for Uber, I need that someone maintain this spec and update it periodically.
But I think it's a very good example for swagger-editor :+1:
