### ISSUE TITLE
Overly strict security in YouTube API?

### ISSUE THREAD

**Issue by bobby-brennan** [APIs-guru/api-models#32]
https://github.com/APIs-guru/api-models/blob/master/APIs/googleapis.com/youtube/v3/swagger.yaml

e.g. GET /activities requires all these scopes:

            - 'https://www.googleapis.com/auth/youtube'
            - 'https://www.googleapis.com/auth/youtube.force-ssl'
            - 'https://www.googleapis.com/auth/youtube.readonly'

Maybe it's meant to be an OR rather than an AND?

**Comment by IvanGoncharov** [comment]
@bobby-brennan It's looks like you right about it.
Strange thing  is that Google API Expolerer also select all of them: https://developers.google.com/apis-explorer/#p/youtube/v3/youtube.activities.list?part=snippet&home=true&_h=8

Will check other Google APIs and if this behaviour consistent, than I will fix it in converter

**Comment by bobby-brennan** [comment]
Confirmed it's also happening with Google Analytics. I authed with only one
of the two supposedly required scopes and the GET endpoints worked fine

Bobby Brennan
bobby.brennan@gmail.com
