### ISSUE TITLE
Swagger API is now OpenAPI

### ISSUE THREAD

**Issue by darklynx** [APIs-guru/api-models#33]
Looks like specification has gone through re-branding recently, and now it is [OpenAPI](https://github.com/OAI/OpenAPI-Specification/blob/master/versions/2.0.md). It also has a new web-site now: https://openapis.org/

The link to https://github.com/swagger-api/swagger-spec/blob/master/versions/2.0.md and naming "Swagger API", etc. should be updated in [README](https://github.com/APIs-guru/api-models/blob/master/README.md)

**Comment by IvanGoncharov** [comment]
@darklynx Thank you.
Took so long, because I totally missed email notification :(

**Comment by darklynx** [comment]
:+1:
