### ISSUE TITLE
Invalid definitions

### ISSUE THREAD

**Issue by darosh** [APIs-guru/api-models#36]
According to http://online.swagger.io/validator

- http://online.swagger.io/validator/debug?url=https://apis-guru.github.io/api-models/trello.com/1.0/swagger.json
- http://online.swagger.io/validator/debug?url=https://apis-guru.github.io/api-models/googleapis.com/storagetransfer/v1/swagger.json
- http://online.swagger.io/validator/debug?url=https://apis-guru.github.io/api-models/watchful.li/1.0.0/swagger.json
- http://online.swagger.io/validator/debug?url=https://apis-guru.github.io/api-models/plenigo.com/2.0.0/swagger.json
- http://online.swagger.io/validator/debug?url=https://apis-guru.github.io/api-models/reactome.org/1.0/swagger.json
- http://online.swagger.io/validator/debug?url=https://apis-guru.github.io/api-models/bbryiot.com/1.0.0/swagger.json

Trello has malformed url: ```"authorizationUrl": "https:\\/\\/trello.com\\/1\\/appKey\\/generate",```

**Comment by darosh** [comment]
- http://online.swagger.io/validator/debug?url=https://apis-guru.github.io/api-models/googleapis.com/cloudtrace/v1/swagger.json

**Comment by darosh** [comment]
adding validator badge to list view at http://darosh.github.io/angular-swagger-ui-material/hub.html 

![image](https://cloud.githubusercontent.com/assets/297320/13557537/795bd0e2-e3f2-11e5-9ad6-aac6bc21f3c9.png)

**Comment by IvanGoncharov** [comment]
@darosh Thank you for reporting this issue. I need feedback in order to make this project better.

It's a problem with [validator-badge](https://github.com/swagger-api/validator-badge).
Because `properties` isn't mandatory field, and it looks like this already fixed: https://github.com/swagger-api/swagger-parser/pull/165
So it will be fixed in the next release.

To valid specs I use [sway](https://github.com/apigee-127/sway) because it provide a lot of [additional validations](https://github.com/apigee-127/sway/blob/master/docs/README.md#semantic-validation).

**Comment by IvanGoncharov** [comment]
@darosh I fixed trello locally and also notified its author.

**Comment by IvanGoncharov** [comment]
@darosh By the way you can add logo for each API.
For example of how to implement it see this: http://apis-guru.github.io/
Here is source code: https://github.com/APIs-guru/APIs-guru.github.io

**Comment by darosh** [comment]
@IvanGoncharov thanks for crystal clear explanation, it is always good to know you have some validation in place

Regarding logos and hub: 

- they have various size, ratio and quality and in my opinion they would need some preprocessing [not to be scaled in browser](http://stackoverflow.com/questions/9312584/whats-the-rationale-behind-the-yslow-rule-dont-scale-images-in-html) and perhaps merging into single CSS sprite image might be a good idea too
- Google Books logo is outdated for example
- [hub.html](http://darosh.github.io/angular-swagger-ui-material/hub.html) 
 - has no final design but I will probably prefer to keep it simple without logos, using the :rainbow: [generator](https://github.com/darosh/angular-swagger-ui-material/blob/master/lib/api-models-rainbows/index.js) based on logo colors,
 - right now I just need the links to the Swagger UI I work on, maybe later I will change the cards into something expandable showing more metadata you provide in the list.json including logos...

**Comment by IvanGoncharov** [comment]
@darosh 
>  it is always good to know you have some validation in place

It's bigger showstopper I have for adding new APIs. I need to manually fix them before adding into the collection. You can see fixup patches [here](https://github.com/APIs-guru/api-models/search?utf8=%E2%9C%93&q=filename%3Afixup.yaml).

> they have various size, ratio and quality and in my opinion they would need some preprocessing

If you use my API you actually using caching logos from [here](https://github.com/APIs-guru/api-models/tree/gh-pages/cache). So I already have mechanism for doing preprocessing, so I can scale non-svg images and provide them in couple of sizes.

> single CSS sprite image

One image for all collection will be huge. 
So right now you page is rendered from up to bottom and user don't care that some logo at botom of page still downloading. In case of packed logos user need to wait for all of them to download.

All my images are served from cache on github so browser reuse same connections and it's pretty efective already.

> has no final design but I will probably prefer to keep it simple without logos

If you have some idea how I can make situations with logo better, feel free to suggest it here.
Obviously I can't manually process each logo, but I can make some preprocessing steps.
