### ISSUE TITLE
Figure.NZ API has been retired

### ISSUE THREAD

**Issue by darosh** [APIs-guru/api-models#37]
> The early preview release of the Figure.NZ API has been retired.
> Our intention is to release a new API before the end of 2016, 
> but this depends on other platform features and we do not have a firm release date at this time.

Pasted from https://figure.nz/api/

**Comment by IvanGoncharov** [comment]
@darosh Thank you.
I finally see Wikipedia part of project description start to working.
People suggesting new API and helping to cleanup existing.
