### ISSUE TITLE
data2crm.com is outdated

### ISSUE THREAD

**Issue by darosh** [APIs-guru/api-models#38]
https://github.com/APIs-guru/api-models/tree/master/APIs/data2crm.com

See x-origin: http://api.data2crm.com/docs/ref/get-swagger-v2

**Comment by IvanGoncharov** [comment]
It's really funny that yesterday I updated them but forget push changes.
So it's a really interesting coincidence.

**Comment by IvanGoncharov** [comment]
@darosh Had some problem with deploying on `gh-pages` so couldn't update API.
But finally released update version both in repo and API.

Also please check #40
I will try to be more public in future.
