### ISSUE TITLE
ExaVault

### ISSUE THREAD

**Issue by darosh** [APIs-guru/api-models#39]
ExaVault has GET only API (GET method for creating and deleting!) but they mention they provide "safer" POST alternative methods undocumented in swagger.

https://www.exavault.com/developer/api-docs/

> ExaVault supports both POST (recommended when requesting large data sets) 
> and GET operations, and requires an API key in order to use. 

It is pretty important information.

External docs and/or description patch could help.

*Note: GET only approach + server side + user with WGET tool is a recipe for disaster. :smiley:*

**Comment by IvanGoncharov** [comment]
@darosh Thank you for reporting.
I try to keep maintenance cost is low as possible, to allow this collection to grow.
So my main principle is to be as close as possible to owner's spec, so I only apply small patches with fixes and additional info.

Please see changes in bda8f7b15a6405965b57b032ff9d4454c9a9bceb.
