### ISSUE TITLE
raml-apis

### ISSUE THREAD

**Issue by darosh** [APIs-guru/api-models#44]
https://github.com/raml-apis looks like interesting collection

I can see few imported already: https://github.com/APIs-guru/api-models/search?utf8=%E2%9C%93&q=raml-apis

**Comment by IvanGoncharov** [comment]
@darosh On a surface, it looks very promising.
But if you go deeper, you will see couple things:
 - They manually create those collections in some kind visual tool. Which is very buggy and it forced me to write [big chunk](https://github.com/APIs-guru/raml-to-swagger/blob/master/src/index.js#L349-L450) to fix all part of mistakes. But I still needed to fix many mistakes [manually](https://github.com/APIs-guru/api-models/blob/master/APIs/github.com/v3/fixup.yaml).
 -  They don't accept [my PRs](https://github.com/raml-apis/GitHub/pulls) or react to [issue](https://github.com/raml-apis/GitHub/issues/6).
 - And most important they don't update their specs.

So by using their specs I give people the false impression that they are correct.
I think not maintained spec is worse than the absence of spec.

They can serve as first step and I can fork repos and improve them.
As an example, I spend 10-12 on adding Github spec.
In retrospect, I think it was better to spend this time on doing scraper for it.
Using [scrape-to-swagger](https://github.com/bobby-brennan/scrape-to-swagger) or simular tool.

**Comment by IvanGoncharov** [comment]
@darosh If you have time and interest.
I have this [list](https://morph.io/IvanGoncharov/API_specifications) of `6549`(without duplication) Swagger 2.0 spec and I have idea of how to filter them using:
https://support.alexa.com/hc/en-us/articles/200461990-Can-I-get-a-list-of-top-sites-from-an-API-

**Comment by darosh** [comment]
@IvanGoncharov thanks for explanation. 

Looking at CSV from morph.io: can you filter out things containing: ```example, sample, test, fixture, petstore, /pet\d+store/``` to make it shorter?

**Comment by IvanGoncharov** [comment]
@darosh I don't want to filter on `morph.io` level. Since it could be used for other purposes.
It's always better to have raw data in DB and do filtering on queries.
I did initial filtering of ~1k specs which I can share if needed.
And I also had idea to scrape all repos from here: https://github.com/swagger-api/swagger.io/blob/wordpress/integrations/open-source.md

It would be cool to write a tool which  classification on all those criterias including one that you suggested. But it should be separate tool which just query morph.io

**Comment by IvanGoncharov** [comment]
@darosh It also has `hash` collumn so you can easily find duplicates.

**Comment by IvanGoncharov** [comment]
@darosh I constantly doing the same mistake, creating parallel discussions inside issues.
I will try my best to stop doing that.
If you have ideas about `morph.io` let's discuss in on Gitter or on a new issue.
