### ISSUE TITLE
link errors in https://apis-guru.github.io/api-models/

### ISSUE THREAD

**Issue by sanchojaf** [APIs-guru/api-models#47]
When I click in the link I have a 404 error.

https://apis-guru.github.io/api-models/

for example

https://apis-guru.github.io/api-models/audiosear.ch/1.0.0/1

**Comment by IvanGoncharov** [comment]
@sanchojaf Fixed. Thank you for reporting it.
Just for better understanding. How do you use this HTML file?

**Comment by sanchojaf** [comment]
Cool, was a casual visit to this page, I don't used frequently



2016-03-17 10:18 GMT-04:00 Ivan Goncharov <notifications@github.com>:

**Comment by IvanGoncharov** [comment]
I have a plan to move it into a separate repo.
Some people confused it with actual API and wrote a parser for it.
I will replace it with simple HTML  with links to API doc and a new location of the list.
It will also simplify my deploy scripts.
@sanchojaf What do you think?
