### ISSUE TITLE
PollenCheck API is deprecated

### ISSUE THREAD

**Issue by maryguirola** [APIs-guru/api-models#48]
PollenCheck announced: 
"I regret to inform everyone that all PollenCheck services will be fully retired after a 1-month period ending on March 15, 2016....
PollenCheck public API will not be accessible after March 14, 2016.
PollenCheck API is deprecated. Do not use it longer."

**Comment by IvanGoncharov** [comment]
@maryguirola Thank you for reporting this.
I don't have the resources to monitor APIs, that is why your help is invaluable for this project.
One suggesting if you cite some document please provide the link to it.

**Comment by maryguirola** [comment]
@IvanGoncharov you mean the document where Pollencheck announced its retirement? It's here: http://www.pollencheck.eu/end

**Comment by IvanGoncharov** [comment]
@maryguirola I found it through Google.
Just a tip for you for a future issue.
It will make my work a little bit easier.
