### ISSUE TITLE
Request Baskets service

### ISSUE THREAD

**Issue by darklynx** [APIs-guru/api-models#55]
Hi,

I've got a simple service to collect and analyze HTTP requests which is useful for QA and testing purposes (write automated tests for web-hook, HTTP redirects and notifications, or even to test REST clients). Something similar to http://requestb.in but entirely open source.

The [Request Baskets](https://rbaskets.in) service is running at https://rbaskets.in but can be deployed by anybody for it is an open source project: https://github.com/darklynx/request-baskets

The RESTful API is documented in Swagger (OpenAPI) format and can be found here: https://github.com/darklynx/request-baskets/blob/master/doc/api-swagger.yaml

It would be great to see my API in your collection!
Thanks

**Comment by IvanGoncharov** [comment]
@darklynx Do you have any logo?

**Comment by darklynx** [comment]
not yet :) I'm planning to have one later.

right now something like this can be used: https://www.iconfinder.com/icons/1055098/basket_cart_shopping_icon#size=128 (I'm not sure how well GPL license is applied to graphics though)

do you need a fixed location (URL) for logo? What is preferred format for the logo PNG, ICO?

**Comment by IvanGoncharov** [comment]
@darklynx Yes, fixed location somewhere inside you repo would be superb.
I prefer SVG since it's scalable.
So you can create `logo.svg` somewhere in your repo and update it when you change the logo.

**Comment by IvanGoncharov** [comment]
@darklynx Added API in 9aa2147. But please provide logo.
I can't leave with one more API without logo :sob:

**Comment by darklynx** [comment]
I decided to draw my own logo :) here it is: https://github.com/darklynx/request-baskets/blob/master/doc/logo.svg

I'm not sure what is the default preferred size, my logo now is 512x512, but as you have already mentioned SVG scales in both directions. I'm open to suggestions.

**Comment by IvanGoncharov** [comment]
@darklynx I added the logo. Thanks for letting me know about your Swagger file.
