### ISSUE TITLE
Objects with empty property names in sendgrid.com v3.0

### ISSUE THREAD

**Issue by sergey-tihon** [APIs-guru/api-models#56]
sendgrid.com v3.0 schema
https://apis-guru.github.io/api-models/sendgrid.com/3.0/swagger.json

has path `/categories/stats/sums` with very strange response type
```
            "schema": {
              "properties": {
                "": {
                  "$ref": "#/definitions/category_stats"
                }
              },
              "type": "object"
            }
```
It is object with `empty name` property of type `#/definitions/category_stats`
I believe that this is incorrect type definition // @IvanGoncharov

**Comment by IvanGoncharov** [comment]
@sergey-tihon Reported back to SendGrid if they don't react in couple days, I will make fix in this repo.
Will it work for you?

**Comment by sergey-tihon** [comment]
Yes, thank you.

**Comment by IvanGoncharov** [comment]
@sergey-tihon Sendgrid fixed this issue I checked diff and it looks like correct fix.
Can you please check it on your side?

**Comment by sergey-tihon** [comment]
Yes, it is OK now.
Thank you @IvanGoncharov
