### ISSUE TITLE
BBC iBL API spec

### ISSUE THREAD

**Issue by MikeRalphson** [APIs-guru/api-models#58]
And another public BBC API.

https://raw.githubusercontent.com/Mermade/bbcparse/master/iblApi/swagger.json

This one has an automatically generated response model derived from the official JSON schema. The BBC Nitro spec will have its response format documented soon too, as I have managed to programmatically convert the official XML Schema to JSON schema.

Mike

**Comment by IvanGoncharov** [comment]
@MikeRalphson Cool thanks a lot.
One thing, can you please make  `x-logo` to follow this spec:
https://github.com/Rebilly/ReDoc/blob/master/docs/redoc-vendor-extensions.md#logo-object

**Comment by MikeRalphson** [comment]
x-logo fixed.
