### ISSUE TITLE
Repository cannot be fully checked out under Windows

### ISSUE THREAD

**Issue by MikeRalphson** [APIs-guru/api-models#69]
````
Cloning into 'api-models'...
remote: Counting objects: 18463, done.
remote: Compressing objects: 100% (299/299), done.
remote: Total 18463 (delta 170), reused 18 (delta 18), pack-reused 18078
Receiving objects: 100% (18463/18463), 27.31 MiB | 602.00 KiB/s, done.
Resolving deltas: 100% (6403/6403), done.
Checking connectivity... done.
error: Invalid path 'APIs/firebrowse.org/1.1.28 (2016-04-22 17:03:55 12f7dc6c7149b63acbf0d907)/swagger.yaml'
error: Invalid path 'APIs/statsocial.com/1.0.0./swagger.yaml'
Checking out files:  100% (513/513)
````

The colons in the date/time-stamp are drive letter specifiers and I believe the final period in 1.0.0./ is trying to create an empty pathname component.

**Comment by IvanGoncharov** [comment]
@MikeRalphson I fixed `firebrowse.org` API. And start using [node-sanitize-filename](https://github.com/parshap/node-sanitize-filename) to prevent the same problem in the future.

As for `APIs/statsocial.com/1.0.0./swagger.yaml` I don't quite understand what is the problem with it.
Can please investigate it more and if needed submit PR to the `node-sanitize-filename` lib.

**Comment by MikeRalphson** [comment]
From [here](https://msdn.microsoft.com/en-us/library/aa365247(v=vs.85).aspx):

"Do not end a file or directory name with a space or a period. Although the underlying file system may support such names, the Windows shell and user interface does not."

I will have a look at fixing the regex used by the sanitisation lib.

**Comment by IvanGoncharov** [comment]
> I will have a look at fixing the regex used by the sanitisation lib.

Funny part is that you need to remove only one symbol in PR:
https://github.com/parshap/node-sanitize-filename/blob/master/index.js#L35
`/^\.+$/` => `/\.+$/`
Plus adding test and documentation.

Thank you for help, will close this issue after your PR will be merged.

**Comment by MikeRalphson** [comment]
v1.6.0 has been released including this fix.

**Comment by IvanGoncharov** [comment]
@MikeRalphson Can you please test it?

**Comment by MikeRalphson** [comment]
Yes this fixes it for me (Windows 10).

**Comment by IvanGoncharov** [comment]
@MikeRalphson Great!
I greatly appreciate you help with making this project more Windows-friendly :+1:

**Comment by G-r-e-g-o-r-y** [comment]
Hi, I have the same issue 

`Cloning into 'openapi-directory'...
remote: Enumerating objects: 174479, done.
...
error: invalid path 'APIs/statsocial.com/1.0.0./openapi.yaml'
fatal: unable to checkout working tree
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'`

Windows is not happy with the final "."
Could this be removed ?

Thank you
