### ISSUE TITLE
Add Drama API

### ISSUE THREAD

**Issue by zaifei5** [APIs-guru/api-models#77]
## It would be also useful if you provided a link to the official API docs and official logo ##

**Comment by IvanGoncharov** [comment]
Hi @zaifei5,

Can you please provide link to API spec in any popular format (OpenAPI, Swagger, RAML, WADL, ...)?
Without it I can't add API you suggested.

**Comment by IvanGoncharov** [comment]
@imarkahann We added UI form for submitting new APIs: https://apis.guru/add-api
