### ISSUE TITLE
New Sendgrid url

### ISSUE THREAD

**Issue by cbornet** [APIs-guru/api-models#80]
Sendgrid has renamed there swagger project to sendgrid-oai
The new x-origin.url is https://raw.githubusercontent.com/sendgrid/sendgrid-oai/master/oai.json

**Comment by IvanGoncharov** [comment]
@cbornet Thank you.

**Comment by MikeRalphson** [comment]
Twitter logo url is unstable.

![image](https://user-images.githubusercontent.com/21603/27865240-b4c0da22-6189-11e7-9f2c-f35f4c6fa57c.png)
