### ISSUE TITLE
Add Netatmo API

### ISSUE THREAD

**Issue by cbornet** [APIs-guru/api-models#81]
> Please post here link to an API spec in any popular format (OpenAPI, Swagger, RAML, WADL, ...) 

https://raw.githubusercontent.com/cbornet/netatmo-swagger-decl/master/swagger.json

> It would be also useful if you provided a link to the official API docs and official logo

* Official API docs : https://dev.netatmo.com/dev/resources/technical/reference
* Logo : https://dev.netatmo.com/images/common/netatmo-connect-horiz.png
* Where to create an app and get credentials : https://dev.netatmo.com/dev/createanapp

Note : this is an unofficial swagger spec which I maintain so I can adjust the spec if needed.

**Comment by IvanGoncharov** [comment]
@cbornet Great, it's ideal.
I will add your API today :)

**Comment by IvanGoncharov** [comment]
@cbornet I added your API into the catalog.
Just one final question, is it official spec?
Meaning it was created by Netatmo or you wrote it independently.
Both works for me but if it unofficial it should be marked as so.

**Comment by cbornet** [comment]
It's unofficial. I wrote it from the Netatmo online doc.

**Comment by IvanGoncharov** [comment]
@cbornet I marked API as unofficial.
>  I wrote it from the Netatmo online doc.

Thank you for such huge amount of work.
