### ISSUE TITLE
Adding GraphHopper Directions API

### ISSUE THREAD

**Issue by karussell** [APIs-guru/api-models#83]
Currently only our [Route Optimization API](https://graphhopper.com/api/1/docs/route-optimization/) has a [swagger spec](https://graphhopper.com/api/1/vrp/swagger.json), but the other APIs will follow at some point :)

We also create the [java client](https://github.com/graphhopper/directions-api-java-client#route-optimization-api) out of the spec which is really nice :)

**Comment by IvanGoncharov** [comment]
@karussell Thank you for submission.
I already added your API on Nov 16, 2015 :)
But it's really great to collaborate with API owners, please check if your API correctly represented:
https://github.com/APIs-guru/api-models/blob/master/APIs/graphhopper.com/1.0/swagger.yaml

P.S. You can use your Swagger spec not only to generate SDKs but also to power API docs.
For example. you can use documentation engine we developed for one of our clients:
https://rebilly.github.io/ReDoc/?url=https://apis-guru.github.io/api-models/graphhopper.com/1.0/swagger.yaml
Here is demo with all of the features:
https://rebilly.github.io/ReDoc/

**Comment by karussell** [comment]
Oh, wow & ups. Never thought that we are already in the list and so I didn't care reading :)
Thanks!

>  But it's really great to collaborate with API owners, please check if your API correctly represented:

Looks good. Do you update this somehow? As we often add new features.

> P.S. You can use your Swagger spec not only to generate SDKs but also to power API docs.

Yeah, we know and did, but at the end it was more descriptive and readable for our customers via self-written docs.

Thanks for the link to rebilly&redoc we'll reconsider this and think about it :) !

BTW: something is wrong with my font (firefox&linux) - see the 'pagination': 
![billy](https://cloud.githubusercontent.com/assets/129644/15678494/d2b5aeb6-274e-11e6-9849-410c2f9361d1.png)

**Comment by IvanGoncharov** [comment]
> Looks good. Do you update this somehow? As we often add new features.

@karussell Yes, see this:
https://github.com/APIs-guru/api-models#update-procedure

> BTW: something is wrong with my font (firefox&linux) - see the 'pagination': 
Thank you for reporting it :+1:
Which browser&OS are you using?

**Comment by karussell** [comment]
> Thank you for reporting it :+1:
> Which browser&OS are you using?

firefox 46.0.1 under ubuntu 14.04.1 with 3.16.0-71-generic
