### ISSUE TITLE
Add teste API

### ISSUE THREAD

**Issue by RodrigoWP** [APIs-guru/api-models#84]
## It would be also useful if you provided a link to the official API docs and official logo ##

**Comment by IvanGoncharov** [comment]
@RodrigoWP Thank you for interest in our project :)
We plan to add a real submit form in a couple of days.
I will send you a link when will have a working prototype.

**Comment by IvanGoncharov** [comment]
@RodrigoWP Here is a link: http://apis-guru.github.io/add-api/
