### ISSUE TITLE
Add "Brand Lovers MarketPlace Seller API v1" API

### ISSUE THREAD

**Issue by rturk** [APIs-guru/api-models#88]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://github.com/brandlovers/marketplace-api-documentation/blob/master/brandlovers-marketplace-api-v1.json
**Name**: Brand Lovers MarketPlace Seller API v1

**Comment by IvanGoncharov** [comment]
@rturk Thank you.
Can you please add URL to your logo?
If would be ideal if you host it in the same repo.

**Comment by IvanGoncharov** [comment]
@rturk Just added your API into collection.
For now used following logo URL: https://brandlovers.com/static/img/logo/BL_white_balao_35px.png
