### ISSUE TITLE
Add "Email Verifier API" API

### ISSUE THREAD

**Issue by roshanjonah** [APIs-guru/api-models#95]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: YES
**Url**: https://www.emailverifierapp.com/email-verification-api-for-developers/
**Name**: Email Verifier API

**Comment by IvanGoncharov** [comment]
@jonahassociates Thank you for submission.
But URL that you submit is points on HTML docs.
To add your API we need spec in of the popular format(Swagger, RAML, WADL, etc.).

P.S. here is good tutorial on how to do this https://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-1-introduction/

**Comment by IvanGoncharov** [comment]
@roshanjonah Sadly I can't API without a machine-readable spec 😭 
Please feel free to reopen this issue when you will have such spec.
