### ISSUE TITLE
Add "Channel4" API

### ISSUE THREAD

**Issue by MikeRalphson** [APIs-guru/api-models#96]
**Format**: OpenAPI(fka Swagger) 2.0
**Official**: NO
**Url**: https://raw.githubusercontent.com/Mermade/openC4/master/c4Api/swagger.json
**Name**: Channel4

This API is for the UK TV broadcaster Channel 4.

**Comment by IvanGoncharov** [comment]
@MikeRalphson Thank you.
Your submission is flawless as always 👍
